### ISSUE TITLE
Offset is not working

### ISSUE THREAD

**Issue by joukevandermaas** [jasonkriss/ember-scroll-to#12]
It looks like this is not in the 0.3 release, because if I use the latest commit of the repo it does work. The 0.3 code does not contain any references to offsets.

See [current release](https://github.com/jasonkriss/ember-scroll-to/blob/29712cec21aeea0e1990ed5f0185ab591ef85620/addon/components/scroll-to.js) vs. [newest commit](https://github.com/jasonkriss/ember-scroll-to/blob/593fdf13f030bdbec9e6072f16bfa68926c66d61/addon/components/scroll-to.js).

Probably the solution is to simply create a new release of the latest commit.

**Comment by jasonkriss** [comment]
You're absolutely right @joukevandermaas. I hadn't cut a release yet since the offset had been added. Just released 0.4.0 though, so that should take care of it for ya!
