### ISSUE TITLE
Calling scrollTo from JS

### ISSUE THREAD

**Issue by lolmaus** [jasonkriss/ember-scroll-to#14]
Sometimes scrolling needs to happen as a result of some programmatic event/promise, not just from immediate user action.

Would be awesome to have something like `this.scrollTo()` in addition to `{{scroll-to}}`.

**Comment by jasonkriss** [comment]
@lolmaus I think that's a great point. However, this is something that is pretty easily handled with jquery so I'm not sure having it as part of this addon would add a ton of value. What do you think?

**Comment by lolmaus** [comment]
Well, adding a jQuery-based action to any element is pretty trivial too. The point of this addon, as I see it, is to provide a clean abstraction.

Also, jQuery is eventually gonna be removed from the default Ember bundle, and this addon could provide a native alternative.

**Comment by jasonkriss** [comment]
The original intent of this addon was to expose a declarative way to specify a link that will cause the page  to scroll to a point in an animated fashion.

That being said, I definitely agree that there are times where this needs to be done in an imperative way. I'm just not sure that the effort necessary make this work in the ember world would be worth it right now. At least until the jquery dependency is removed from Ember, as you mentioned.

If you don't mind putting together a PR though, I'm more than willing to consider it.

Thanks @lolmaus!
